CREATE TABLE IF NOT EXISTS petugas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  wilayah text NOT NULL,
  lingkungan text,
  no_hp text,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS petugas_nama_unique
  ON petugas (upper(trim(nama)));

CREATE INDEX IF NOT EXISTS petugas_wilayah_idx
  ON petugas (wilayah, lingkungan);

CREATE TABLE IF NOT EXISTS koordinator (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  petugas_id integer REFERENCES petugas(id) ON DELETE SET NULL,
  nama text NOT NULL,
  no_hp text,
  aktif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS koordinator_nama_unique
  ON koordinator (upper(trim(nama)));

CREATE TABLE IF NOT EXISTS jadwal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  jam time without time zone NOT NULL,
  petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE RESTRICT,
  koordinator_id integer REFERENCES koordinator(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'terjadwal',
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jadwal_status_check
    CHECK (status IN ('draft', 'terjadwal', 'selesai', 'batal')),
  CONSTRAINT jadwal_petugas_slot_unique
    UNIQUE (tanggal, jam, petugas_id)
);

CREATE INDEX IF NOT EXISTS jadwal_tanggal_jam_idx
  ON jadwal (tanggal, jam);

CREATE INDEX IF NOT EXISTS jadwal_petugas_idx
  ON jadwal (petugas_id, tanggal, jam);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS petugas_set_updated_at ON petugas;
CREATE TRIGGER petugas_set_updated_at
BEFORE UPDATE ON petugas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS koordinator_set_updated_at ON koordinator;
CREATE TRIGGER koordinator_set_updated_at
BEFORE UPDATE ON koordinator
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS jadwal_set_updated_at ON jadwal;
CREATE TRIGGER jadwal_set_updated_at
BEFORE UPDATE ON jadwal
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION can_assign_petugas(
  p_petugas_id integer,
  p_tanggal date,
  p_jam time without time zone,
  p_ignore_jadwal_id bigint DEFAULT NULL
)
RETURNS boolean AS $$
DECLARE
  active_petugas_count integer;
  last_assignment_at timestamp;
  used_other_petugas_count integer;
  target_assignment_at timestamp;
BEGIN
  target_assignment_at := p_tanggal + p_jam;

  SELECT count(*)
    INTO active_petugas_count
  FROM petugas
  WHERE aktif = true;

  IF active_petugas_count <= 1 THEN
    RETURN true;
  END IF;

  SELECT max(j.tanggal + j.jam)
    INTO last_assignment_at
  FROM jadwal j
  WHERE j.petugas_id = p_petugas_id
    AND j.status <> 'batal'
    AND (p_ignore_jadwal_id IS NULL OR j.id <> p_ignore_jadwal_id)
    AND (j.tanggal + j.jam) < target_assignment_at;

  IF last_assignment_at IS NULL THEN
    RETURN true;
  END IF;

  SELECT count(DISTINCT j.petugas_id)
    INTO used_other_petugas_count
  FROM jadwal j
  JOIN petugas p ON p.id = j.petugas_id
  WHERE p.aktif = true
    AND j.petugas_id <> p_petugas_id
    AND j.status <> 'batal'
    AND (p_ignore_jadwal_id IS NULL OR j.id <> p_ignore_jadwal_id)
    AND (j.tanggal + j.jam) > last_assignment_at
    AND (j.tanggal + j.jam) < target_assignment_at;

  RETURN used_other_petugas_count >= active_petugas_count - 1;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION enforce_petugas_rotation()
RETURNS trigger AS $$
DECLARE
  is_petugas_active boolean;
BEGIN
  IF NEW.status = 'batal' THEN
    RETURN NEW;
  END IF;

  SELECT aktif
    INTO is_petugas_active
  FROM petugas
  WHERE id = NEW.petugas_id;

  IF is_petugas_active IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'Petugas tidak aktif atau tidak ditemukan.';
  END IF;

  IF NOT can_assign_petugas(NEW.petugas_id, NEW.tanggal, NEW.jam, NEW.id) THEN
    RAISE EXCEPTION 'Petugas ini sudah mendapat giliran. Habiskan semua petugas aktif lebih dulu sebelum ditugaskan kembali.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS jadwal_enforce_petugas_rotation ON jadwal;
CREATE TRIGGER jadwal_enforce_petugas_rotation
BEFORE INSERT OR UPDATE OF tanggal, jam, petugas_id, status ON jadwal
FOR EACH ROW
EXECUTE FUNCTION enforce_petugas_rotation();
