ALTER TABLE jadwal
  ADD COLUMN IF NOT EXISTS jumlah_petugas integer NOT NULL DEFAULT 1;

UPDATE jadwal
SET jam = time '00:00'
WHERE jam IS NULL;

ALTER TABLE jadwal
  ALTER COLUMN jam SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'jadwal_jumlah_petugas_check'
  ) THEN
    ALTER TABLE jadwal
      ADD CONSTRAINT jadwal_jumlah_petugas_check CHECK (jumlah_petugas > 0);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS jadwal_petugas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jadwal_id bigint NOT NULL REFERENCES jadwal(id) ON DELETE CASCADE,
  petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE RESTRICT,
  urutan integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jadwal_petugas_petugas_unique
    UNIQUE (jadwal_id, petugas_id),
  CONSTRAINT jadwal_petugas_urutan_unique
    UNIQUE (jadwal_id, urutan),
  CONSTRAINT jadwal_petugas_urutan_check
    CHECK (urutan > 0)
);

CREATE INDEX IF NOT EXISTS jadwal_petugas_petugas_idx
  ON jadwal_petugas (petugas_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'jadwal'
      AND column_name = 'petugas_id'
  ) THEN
    INSERT INTO jadwal_petugas (jadwal_id, petugas_id, urutan)
    SELECT
      j.id,
      j.petugas_id,
      1
    FROM jadwal j
    WHERE j.petugas_id IS NOT NULL
    ON CONFLICT (jadwal_id, petugas_id) DO NOTHING;
  END IF;
END;
$$;

UPDATE jadwal j
SET jumlah_petugas = sub.assigned_count
FROM (
  SELECT jadwal_id, count(*)::integer AS assigned_count
  FROM jadwal_petugas
  GROUP BY jadwal_id
) sub
WHERE sub.jadwal_id = j.id
  AND j.jumlah_petugas < sub.assigned_count;

DROP TRIGGER IF EXISTS jadwal_enforce_petugas_rotation ON jadwal;

CREATE OR REPLACE FUNCTION can_assign_petugas(
  p_petugas_id integer,
  p_tanggal date,
  p_jam time without time zone,
  p_ignore_jadwal_id bigint DEFAULT NULL
)
RETURNS boolean AS $$
DECLARE
  active_petugas_count integer;
  last_assignment_at timestamp;
  used_other_petugas_count integer;
  target_assignment_at timestamp;
BEGIN
  target_assignment_at := p_tanggal + p_jam;

  SELECT count(*)
    INTO active_petugas_count
  FROM petugas
  WHERE aktif = true;

  IF active_petugas_count <= 1 THEN
    RETURN true;
  END IF;

  SELECT max(j.tanggal + j.jam)
    INTO last_assignment_at
  FROM jadwal_petugas jp
  JOIN jadwal j ON j.id = jp.jadwal_id
  WHERE jp.petugas_id = p_petugas_id
    AND j.status <> 'batal'
    AND (p_ignore_jadwal_id IS NULL OR j.id <> p_ignore_jadwal_id)
    AND (j.tanggal + j.jam) < target_assignment_at;

  IF last_assignment_at IS NULL THEN
    RETURN true;
  END IF;

  SELECT count(DISTINCT jp.petugas_id)
    INTO used_other_petugas_count
  FROM jadwal_petugas jp
  JOIN jadwal j ON j.id = jp.jadwal_id
  JOIN petugas p ON p.id = jp.petugas_id
  WHERE p.aktif = true
    AND jp.petugas_id <> p_petugas_id
    AND j.status <> 'batal'
    AND (p_ignore_jadwal_id IS NULL OR j.id <> p_ignore_jadwal_id)
    AND (j.tanggal + j.jam) > last_assignment_at
    AND (j.tanggal + j.jam) < target_assignment_at;

  RETURN used_other_petugas_count >= active_petugas_count - 1;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION enforce_jadwal_petugas_rotation()
RETURNS trigger AS $$
DECLARE
  is_petugas_active boolean;
  target_tanggal date;
  target_jam time without time zone;
  target_status text;
BEGIN
  SELECT tanggal, jam, status
    INTO target_tanggal, target_jam, target_status
  FROM jadwal
  WHERE id = NEW.jadwal_id;

  IF target_status = 'batal' THEN
    RETURN NEW;
  END IF;

  SELECT aktif
    INTO is_petugas_active
  FROM petugas
  WHERE id = NEW.petugas_id;

  IF is_petugas_active IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'Petugas tidak aktif atau tidak ditemukan.';
  END IF;

  IF NOT can_assign_petugas(NEW.petugas_id, target_tanggal, target_jam, NEW.jadwal_id) THEN
    RAISE EXCEPTION 'Petugas ini sudah mendapat giliran. Habiskan semua petugas aktif lebih dulu sebelum ditugaskan kembali.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS jadwal_petugas_enforce_rotation ON jadwal_petugas;
CREATE TRIGGER jadwal_petugas_enforce_rotation
BEFORE INSERT OR UPDATE OF jadwal_id, petugas_id ON jadwal_petugas
FOR EACH ROW
EXECUTE FUNCTION enforce_jadwal_petugas_rotation();
