CREATE TABLE IF NOT EXISTS penugasan_petugas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jadwal_id bigint NOT NULL REFERENCES jadwal(id) ON DELETE CASCADE,
  jadwal_petugas_id bigint NOT NULL REFERENCES jadwal_petugas(id) ON DELETE CASCADE,
  petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE RESTRICT,
  tanggal date NOT NULL,
  jam time without time zone NOT NULL,
  status text NOT NULL DEFAULT 'terjadwal',
  assigned_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT penugasan_petugas_jadwal_petugas_unique
    UNIQUE (jadwal_petugas_id),
  CONSTRAINT penugasan_petugas_jadwal_petugas_petugas_unique
    UNIQUE (jadwal_id, petugas_id),
  CONSTRAINT penugasan_petugas_status_check
    CHECK (status IN ('terjadwal', 'batal'))
);

CREATE INDEX IF NOT EXISTS penugasan_petugas_petugas_idx
  ON penugasan_petugas (petugas_id);

CREATE INDEX IF NOT EXISTS penugasan_petugas_tanggal_jam_idx
  ON penugasan_petugas (tanggal, jam);

CREATE OR REPLACE FUNCTION normalize_penugasan_status(p_jadwal_status text)
RETURNS text AS $$
BEGIN
  IF p_jadwal_status = 'batal' THEN
    RETURN 'batal';
  END IF;

  RETURN 'terjadwal';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

INSERT INTO penugasan_petugas (
  jadwal_id,
  jadwal_petugas_id,
  petugas_id,
  tanggal,
  jam,
  status
)
SELECT
  j.id,
  jp.id,
  jp.petugas_id,
  j.tanggal,
  j.jam,
  normalize_penugasan_status(j.status)
FROM jadwal_petugas jp
JOIN jadwal j ON j.id = jp.jadwal_id
ON CONFLICT (jadwal_petugas_id) DO UPDATE SET
  jadwal_id = EXCLUDED.jadwal_id,
  petugas_id = EXCLUDED.petugas_id,
  tanggal = EXCLUDED.tanggal,
  jam = EXCLUDED.jam,
  status = EXCLUDED.status,
  updated_at = now();

CREATE OR REPLACE FUNCTION sync_penugasan_from_jadwal_petugas()
RETURNS trigger AS $$
DECLARE
  target_tanggal date;
  target_jam time without time zone;
  target_status text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM penugasan_petugas
    WHERE jadwal_petugas_id = OLD.id;
    RETURN OLD;
  END IF;

  SELECT tanggal, jam, status
    INTO target_tanggal, target_jam, target_status
  FROM jadwal
  WHERE id = NEW.jadwal_id;

  INSERT INTO penugasan_petugas (
    jadwal_id,
    jadwal_petugas_id,
    petugas_id,
    tanggal,
    jam,
    status
  )
  VALUES (
    NEW.jadwal_id,
    NEW.id,
    NEW.petugas_id,
    target_tanggal,
    target_jam,
    normalize_penugasan_status(target_status)
  )
  ON CONFLICT (jadwal_petugas_id) DO UPDATE SET
    jadwal_id = EXCLUDED.jadwal_id,
    petugas_id = EXCLUDED.petugas_id,
    tanggal = EXCLUDED.tanggal,
    jam = EXCLUDED.jam,
    status = EXCLUDED.status,
    updated_at = now();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS jadwal_petugas_sync_penugasan ON jadwal_petugas;
CREATE TRIGGER jadwal_petugas_sync_penugasan
AFTER INSERT OR UPDATE OF jadwal_id, petugas_id ON jadwal_petugas
FOR EACH ROW
EXECUTE FUNCTION sync_penugasan_from_jadwal_petugas();

CREATE OR REPLACE FUNCTION sync_penugasan_from_jadwal()
RETURNS trigger AS $$
BEGIN
  UPDATE penugasan_petugas
  SET
    tanggal = NEW.tanggal,
    jam = NEW.jam,
    status = normalize_penugasan_status(NEW.status),
    updated_at = now()
  WHERE jadwal_id = NEW.id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS jadwal_sync_penugasan ON jadwal;
CREATE TRIGGER jadwal_sync_penugasan
AFTER UPDATE OF tanggal, jam, status ON jadwal
FOR EACH ROW
EXECUTE FUNCTION sync_penugasan_from_jadwal();

CREATE OR REPLACE VIEW petugas_penugasan_count AS
SELECT
  p.id AS petugas_id,
  count(pp.id)::integer AS total_penugasan
FROM petugas p
LEFT JOIN penugasan_petugas pp
  ON pp.petugas_id = p.id
  AND pp.status <> 'batal'
GROUP BY p.id;
