CREATE TABLE IF NOT EXISTS petugas_jadwal_waktu_pilihan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE CASCADE,
  hari smallint NOT NULL,
  jam time without time zone NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT petugas_jadwal_waktu_pilihan_unique
    UNIQUE (petugas_id, hari, jam),
  CONSTRAINT petugas_jadwal_waktu_pilihan_hari_check
    CHECK (hari BETWEEN 0 AND 6)
);

CREATE INDEX IF NOT EXISTS petugas_jadwal_waktu_pilihan_petugas_idx
  ON petugas_jadwal_waktu_pilihan (petugas_id);

CREATE OR REPLACE FUNCTION petugas_boleh_jadwal(
  p_petugas_id integer,
  p_jadwal_id bigint
)
RETURNS boolean AS $$
DECLARE
  target_hari smallint;
  target_jam time without time zone;
BEGIN
  SELECT extract(dow from tanggal)::smallint, jam
    INTO target_hari, target_jam
  FROM jadwal
  WHERE id = p_jadwal_id;

  IF target_hari IS NULL OR target_jam IS NULL THEN
    RETURN false;
  END IF;

  RETURN
    NOT EXISTS (
      SELECT 1
      FROM petugas_jadwal_waktu_pilihan
      WHERE petugas_id = p_petugas_id
    )
    OR EXISTS (
      SELECT 1
      FROM petugas_jadwal_waktu_pilihan
      WHERE petugas_id = p_petugas_id
        AND hari = target_hari
        AND jam = target_jam
    );
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION enforce_jadwal_petugas_rotation()
RETURNS trigger AS $$
DECLARE
  is_petugas_active boolean;
  target_tanggal date;
  target_jam time without time zone;
  target_status text;
BEGIN
  SELECT tanggal, jam, status
    INTO target_tanggal, target_jam, target_status
  FROM jadwal
  WHERE id = NEW.jadwal_id;

  IF target_status = 'batal' THEN
    RETURN NEW;
  END IF;

  SELECT aktif
    INTO is_petugas_active
  FROM petugas
  WHERE id = NEW.petugas_id;

  IF is_petugas_active IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'Petugas tidak aktif atau tidak ditemukan.';
  END IF;

  IF NOT petugas_boleh_jadwal(NEW.petugas_id, NEW.jadwal_id) THEN
    RAISE EXCEPTION 'Petugas ini hanya boleh ditugaskan pada hari dan jam yang dipilih di detail petugas.';
  END IF;

  IF NOT can_assign_petugas(NEW.petugas_id, target_tanggal, target_jam, NEW.jadwal_id) THEN
    RAISE EXCEPTION 'Petugas ini sudah mendapat giliran. Habiskan semua petugas aktif lebih dulu sebelum ditugaskan kembali.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
