-- Add attendance tracking and swap history tables

ALTER TABLE penugasan_petugas
ADD COLUMN IF NOT EXISTS attendance_status text NOT NULL DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS attendance_checked_in_at timestamptz;

ALTER TABLE penugasan_petugas
DROP CONSTRAINT IF EXISTS penugasan_petugas_attendance_status_check;

ALTER TABLE penugasan_petugas
ADD CONSTRAINT penugasan_petugas_attendance_status_check
  CHECK (attendance_status IN ('pending', 'attended'));

CREATE INDEX IF NOT EXISTS penugasan_petugas_attendance_status_idx
  ON penugasan_petugas (attendance_status);

CREATE TABLE IF NOT EXISTS penugasan_petugas_attendance_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penugasan_petugas_id bigint NOT NULL REFERENCES penugasan_petugas(id) ON DELETE CASCADE,
  action text NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS jadwal_petugas_swap_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jadwal_id bigint NOT NULL REFERENCES jadwal(id) ON DELETE CASCADE,
  jadwal_petugas_id bigint NOT NULL,
  from_petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE RESTRICT,
  to_petugas_id integer NOT NULL REFERENCES petugas(id) ON DELETE RESTRICT,
  mode text NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT jadwal_petugas_swap_history_mode_check
    CHECK (mode IN ('manual', 'random'))
);
